pipeline {
    agent any
    
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    def dockerImage = docker.build('iamgedevopseasylearning/s4-pipeline-auth', '.')
                    dockerImage.push()
                }
            }
        }
    }
    
    post {
        success {
            echo 'Docker image build and push successful'
        }
        failure {
            echo 'Docker image build or push failed'
        }
    }
}
